<?php

$text = array(
	'nonconfo_title' => 'No conformidades',
	'nonconfo_processes' => 'Procesos',
	'nonconfo_process_name' => 'Nombre del proceso',
	'nonconfo_add_process' => 'Añadir proceso',
	'nonconfo_edit_process' => 'Editar proceso',
	'nonconfo_view_all' => 'Listado de no conformidades',
	'nonconfo_process_list' => 'Listado de procesos',
	'nonconfo_non_process_exists' => 'Aún no se ha agregado ningún proceso',
	'nonconfo_process_owner' => 'Responsable',
	'nonconfo_actions' => 'Acciones',
	'nonconfo_delete_process' => 'Borrar proceso',
	'nonconfo_rm_process' => 'Eliminar proceso',
	'nonconfo_confirm_rm_process' => '¿Realmente desea eliminar el proceso?',
	'nonconfo_delete_process_success' => 'Proceso eliminado correctamente',
	'nonconfo_id_error' => 'Identificador de proceso inválido',
	'nonconfo_id_error' => 'El proceso solicitado no existe',
	'nonconfo_add_owners' => 'Agregar propietarios de procesos',
	'nonconfo_select_process' => 'Seleccione un proceso',
	'nonconfo_select_owners' => 'Seleccione los propietarios',
	'nonconfo_owners_details' => 'Detalles de propietarios',
	
);

?>