<?php

$text = array(
	'nonconfo_title' => 'No conformidades',
	'nonconfo_process_name' => 'Nombre del proceso',
	'nonconfo_add_process' => 'Añadir proceso',
	'nonconfo_edit_process' => 'Editar proceso',
	'nonconfo_view_all' => 'Listado de no conformidades',
	'nonconfo_process_list' => 'Listado de procesos',
	'nonconfo_non_process_exists' => 'Aún no se ha agregado ningún proceso',
	'nonconfo_process_owner' => 'Responsable',
	'nonconfo_actions' => 'Acciones',
	'nonconfo_delete_process' => 'Borrar proceso',
);

?>